### ISSUE TITLE
Web app to expose DynamoDB settings and whitelist tables

### ISSUE THREAD

**Issue by mlevit-servian** [servian/aws-auto-cleanup#1]
Auto Cleanup interacts with two tables that live within DynamoDB (`auto-cleanup-settings` and `auto-cleanup-whitelist`). In order to enable users to interact with both of these tables in a more user friendly way, a simple to use web app (preferably static in nature) would need to be built.

**Settings**

The settings page should simple expose the table allowing addition, modification and deletion of rows.

**Whitelist**

The whitelist page should allow addition, modification and deletion of rows but should also ensure the `expire_at` column is automatically populated with an EPOCH timestamp of today plus 7 days (this ensures no one except admins can whitelist a resource permanently).

Against each whitelist record, users should have the ability to extend their whitelist from today to today plus 7. This will ensure that without interaction from the users, their whitelisting records will be removed by DynamoDB and consequently removed by Auto Cleanup.

**Comment by JacobHughes** [comment]
I would recommend starting this feature with an API & other required backing services, and supply two endpoints - `POST` to add a resource to the whitelist, `PUT` to increase the TTL for a whitelisted item, `GET` to check if a resource is listed and retrieve the TTL, and `DELETE` to remove an item from the whitelist.
