### ISSUE TITLE
Question: when removed TTL for EC2 instances - they are still skipped due t oTTL

### ISSUE THREAD

**Issue by membra** [servian/aws-auto-cleanup#102]
I wanted to simulate the situation when a newly created ec2 instance will be destroyed as a result of the run.

I created the instance and removed the TTL setting for EC2 instances in dynamodb altogether so that even newly created instances could be destroyed.

...
   "instance": {
    "clean": true,
    "id": "Instance ID"
   },
....

When running in destroy mode after it I see that the EC2 instance is still being skipped because of TTL
![image](https://user-images.githubusercontent.com/53686351/148875616-19a97b12-3034-441d-9b26-965217ef62ee.png)

Does it use some default TTL if none is specified?
How can I simulate a situation when TTL is not applied to a certain resource type?

Thanks!

**Comment by mlevit** [comment]
It does. By default, if the record within DynamoDB cannot be found, it'll default to 7 days. So rather than deleting the record from DynamoDB, just set the `ttl` value to `0`.

**Comment by membra** [comment]
I will check it today and will close if it works as explained - thx!

**Comment by membra** [comment]
@mlevit sorry, just trying to figure out logic still:

I have an EC2 instance that is to be deleted (not in whitelist, not within TTL)
it has an Address, sg attached and Volume attached
SG is marked - to delete
And address and volume as In use
![image](https://user-images.githubusercontent.com/53686351/149708575-369df11f-ec0d-4e89-a9ec-3fca217c51b8.png)


Could you clarify what will eventually be deleted?

**Comment by mlevit** [comment]
Each resource is evaluated mutually exclusively and a lot of times in parallel. Hence why the volume may have been skipped because it was used by the EC2 instance, but the EC2 instance was later deleted.

**Comment by membra** [comment]
@mlevit 

I ran the tool in destroy mode and I see the same,
The EC2 instance was terminated as it was not in whitelist and not below TTL
but the security group and volume stayed as in use
![image](https://user-images.githubusercontent.com/53686351/150045415-222d6633-ae56-46e5-ac0a-b4724ca0de1c.png)

Does it mean that I need to be running it multiple times to properly cleanup the resources?

**Comment by mlevit** [comment]
Like I mentioned before because the cleanup is run in parallel, the security group and volume could have been checked when the EC2 instance was still running.

If you run the app again, it should get rid of the resources unless they're used by another resource.
