### ISSUE TITLE
Deleting resources with resource based policies fails 

### ISSUE THREAD

**Issue by membra** [servian/aws-auto-cleanup#106]
I noticed issues with deletion of KMS keys (and actually any other resource that has resource based access policy)

![image](https://user-images.githubusercontent.com/53686351/152081755-a319b918-ab82-43e9-80ae-52cb4c447034.png)

Though lambda role does have permissions to * when executed through cloudformation - the KMS policy allows only certain roles to delete or access it.

What is the suggested approach with such cases?

**Comment by membra** [comment]
A small addition here -
The issue with KMS keys specifically is that you cannot delete it,

You can schedule a deletion for 7 or 30 days.

Which means that noone will be able to recreate KMS key with same name for at least a week.

**Comment by mlevit** [comment]
@membra that's a tough issue to workaround. You might need to clean up certain Stacks manually as Auto Cleanup won't have the right permission to do so (as you've mentioned already).

**Comment by membra** [comment]
Any chance a possibility (a new feature) can be added to assume elevated role (that is allowed in resource policy)?

**Comment by mlevit** [comment]
Sure we can assume a different role. The follow-up questions would be

1. Which role would the app need to assume?
2. How would the app know a different role needs to be assumed?
3. How would the app have the permissions to assume that role?

**Comment by membra** [comment]
As a suggestion
1) in our case there is an elevated role that does have permissions to delete all resources with resource-based policies (in other companies' cases it might be different of course). So in our case I d know which role it should be.
2) just an idea - a separate parameter - elevated role arn - passed during build / deploy and will be then used for specific cases where it is required
3) that one is a tricky one - since that elevated role is out of the scope of this infra - I assume it might be the separate operation you need to do on that role as a prerequisite - allow it to be assumed by the role under which the cleanup tool is running.

There is a different approach - when creating secrets and keys - allow the cleanup tool role to delete it, but in the case of a big established organizations that means introducing a across the organization policy of creating a certain resource / recreating old resources etc - that is normally a very complicated thing to achieve unfortunately.

For now we of course just clean those up ourselves and in case of KMS related stacks - just adding them now to whitelist,
Cause there is more effort to delete them afterwards than benefits from cleaning those up.

**Comment by mlevit** [comment]
I don't think this can be easily solved. Too many variables in the different organisations can set this up in their own accounts.

I think for now, just keep doing what you're doing and deleting these manually when you need to.
