### ISSUE TITLE
Question: ENIs are not deleted

### ISSUE THREAD

**Issue by membra** [servian/aws-auto-cleanup#107]
**Describe the bug**
When I run the tool, some of the SGs are not getting deleted because they have depended objects
![image](https://user-images.githubusercontent.com/53686351/153787435-a11f8324-88be-4350-8bd9-1bd23c09637a.png)
These objects are ENIs
![image](https://user-images.githubusercontent.com/53686351/153787465-62684c24-0ed7-47c6-8daf-e8930da74ba7.png)

Any reason ENIs are not tackled?

**Comment by mlevit** [comment]
Hey @membra. ENIs aren't very costly and therefore there isn't a real point in tracking them. The main purpose of Auto Cleanup is to reduce your AWS bill. Tracking ENIs also adds more work for users to whitelist them when most ENIs aren't even created by users.

I admit that some of the resources we do track i.e., security groups probably don't need to be tracked as they don't have a monetary impact on your bill. But rather not add more resources at that same level.
