### ISSUE TITLE
Nat gateways whitelisting does not work

### ISSUE THREAD

**Issue by membra** [servian/aws-auto-cleanup#120]
**Describe the bug**
A NAT gateway is in allowlist based on doco:
<html>
<body>

EC2 NAT Gateways | NAT Gateway ID | ec2:instance:nat_gateway_id
-- | -- | --

</body>
</html>

![image](https://user-images.githubusercontent.com/53686351/177440273-bf442163-505c-431e-b2a4-2d686411587d.png)

But it is listed as DELETED after the run

![image](https://user-images.githubusercontent.com/53686351/177440353-4ee0485c-a1ad-41a4-bdf5-bf97c570bec4.png)

**Expected behavior**
NAT gateway is skipped if it is in allowlist

**Comment by membra** [comment]
I suspect the issue might be with the documentation itself...
"nat_gateway" is what is expected, not "instance"

**Comment by mlevit** [comment]
Great pickup @membra. The documentation is wrong. `nat_gateway` is the correct resource.

**Comment by mlevit** [comment]
Fixed https://github.com/servian/aws-auto-cleanup/commit/8dacdc0c5197925b4970778e00599514d621bf01
