### ISSUE TITLE
Error: TypeError: (intermediate value).run is not a function

### ISSUE THREAD

**Issue by DesAWSume** [servian/aws-auto-cleanup#128]
**Describe the bug**
When deploying web module by running npm run deploy:client, it errors out with below message
Error:
TypeError: (intermediate value).run is not a function

**To Reproduce**

1. Go to 'web'

**Expected behavior**
Error:
TypeError: (intermediate value).run is not a function

**Screenshots**

**Stacktrace**
If applicable, add stacktraces to help explain your problem.

```python

```

**Versions (please complete the following information):**

- Serverless Framework: [e.g. 1.42.3]
- boto3: [e.g. 1.9.156]
- botocore: [e.g. 1.12.156]
- moto: [e.g. 1.3.8]
- pytest: [e.g. 4.4.1]

**AWS (please complete the following information):**

- Region: [e.g. ap-southeast-2]

**Additional context**

**Comment by mlevit** [comment]
I believe you have an issue with your `serverless-finch` add-on. Can you try [manually installing v3.0.0](https://www.npmjs.com/package/serverless-finch/v/3.0.0) and trying to deploy again?
