### ISSUE TITLE
Use root device attach time instead of launch time to get EC2 instance age

### ISSUE THREAD

**Issue by atqhg23** [servian/aws-auto-cleanup#129]
**Describe the bug**
Currently, the launch time is used to determine the age of the EC2 instance, but this value is reset when someone restarts the instance allowing users to indefinitely keep an instance from being cleaned up.

**To Reproduce**
1. Launch an EC2 instance
2. Make note of the launch time
3. Stop and start the instance
4. The launch time is updated to when the instance was started

**Expected behavior**
I looked into this and it seems like looking at the root volume attach time is the best way to determine the actual age of an instance.

**Comment by mlevit** [comment]
Thanks for raising this @atqhg23. Really interesting discovery. Let me look into it and see what the best approach would be.

**Comment by atqhg23** [comment]
The issue with using the root volume attach time is that the root volume can be replaced which would return the wrong time if it had been replaced. 

I checked with AWS on this, and it seems like the best approach would be to use the attach time of the instance's primary ENI since the primary ENI cannot de detached or deleted until the EC2 instance is deleted as well. The primary ENI can be identified by looking at the DeviceIndex, the primary ENI will always have the DeviceIndex set to 0.

**Comment by mlevit** [comment]
Thanks for that info @atqhg23. I've made the change within https://github.com/servian/aws-auto-cleanup/tree/better-ec2-launch-time

Mind testing it out for me? 😄

**Comment by atqhg23** [comment]
Will do, thanks!

**Comment by atqhg23** [comment]
This worked! Thanks again for the help
