### ISSUE TITLE
Amazon ECS support

### ISSUE THREAD

**Issue by mlevit-servian** [servian/aws-auto-cleanup#19]

**Comment by lovepurohit** [comment]
Hello melvit-servian,

I would like to work on this issue. I will add the functionality to remove the ECS and all its associated details. Can I work on this issue.

Thank you

**Comment by mlevit** [comment]
@lovepurohit that would be great. Fork the repo and send through a PR when you're ready 👍

**Comment by lovepurohit** [comment]
@mlevit Sure. I'll raise a PR till the end of the week. 

Thank you

**Comment by mlevit** [comment]
Added in 5ad5332452d153b7d94c853f65538439c09b3ebc
