### ISSUE TITLE
[ERROR] Could not generate resource tree. (lambda_handler.py, build_tree(), line 352)

### ISSUE THREAD

**Issue by andreirymar** [servian/aws-auto-cleanup#40]
Everything runs Okay but at the end resource tree cannot be created and copied to s3 bucket.
See last lines I see in Lambda function output.

[INFO] Auto Cleanup completed. (lambda_handler.py, run_cleanup(), line 168)
00:40:31
[ERROR] Could not generate resource tree. (lambda_handler.py, build_tree(), line 352)
00:40:31
[ERROR] invalid syntax (_base.py, line 414) (lambda_handler.py, build_tree(), line 353)
00:40:31
END RequestId: 4d42e55b-b159-4524-bf4e-148447aa73ac

**Comment by mlevit** [comment]
@andreirymar can you head into CloudWatch for this run and send through the logs? Remove anything private from there. I'd like to see where exactly it failed.

**Comment by andreirymar** [comment]
Here's complete output from CloudWatch in attached file.

[CloudWatch logs for AutoCleanup.txt](https://github.com/servian/aws-auto-cleanup/files/4270717/CloudWatch.logs.for.AutoCleanup.txt)

**Comment by mlevit** [comment]
Thanks for that @andreirymar. It looks like you're getting the same error as another user was. I just merged a fixed in #41 that hopefully should fix the DynamoDB error. Could you pull the latest changes and try running it again.

It might not fix the tree building issue, but at least it'll get rid of one of them.

**Comment by andreirymar** [comment]
I think it made it even worse. After I removed everything and did a clean get and deploy, even the first run fails, see attached error logs.
[CloudWatch logs for AutoCleanup March-7-2020.txt](https://github.com/servian/aws-auto-cleanup/files/4302722/CloudWatch.logs.for.AutoCleanup.March-7-2020.txt)
