### ISSUE TITLE
Security group used in auto scaling group launch configuration

### ISSUE THREAD

**Issue by andreirymar** [servian/aws-auto-cleanup#46]
Security group used in auto scaling group launch configuration

**Comment by andreirymar** [comment]
Security group used in auto scaling group launch configuration has been deleted and now auto-scaling group cannot launch EC2 instances.

**Comment by mlevit** [comment]
Hey @andreirymar, please add the security group to the DynamoDB whitelist table. See https://github.com/servian/aws-auto-cleanup#whitelist for configuration settings.

**Comment by andreirymar** [comment]
The deleted security group was part of whitelisted cloud formation. Is that not enough to whitelist cloud formation stack ?

**Comment by mlevit** [comment]
Unfortunately not. Everything is mutually exclusive. You've protected the CloudFormation stack from being deleted, but everything within that stack will be accessed on its own.

**Comment by mlevit** [comment]
@andreirymar I've just merged a changed #55 that will now whitelist all resources within a CloudFormation Stack if the CloudFormation Stack was not deleted due to a whitelist entry or TTL.

You can now just whitelist the Stack without having to worry about the underlying resources.
