### ISSUE TITLE
Generate a report on what resources are deleted and what are whitelisted with some level of operational detail

### ISSUE THREAD

**Issue by tmx-dxiao** [servian/aws-auto-cleanup#49]
**Is your feature request related to a problem? Please describe.**
we are frustrated when we need to generate a report on actions, e.g. what resources are deleted or whitelisted and when. It appears that CW logs has everything logged including when a resource is cleaned up or deleted, but it's all plain text and not so straightforward to extract those actions from all the logs in an organized way.

**Describe the solution you'd like**
If the actions can be recorded on a DynamoDB table with a few attributes, e.g. resource type, resource id, account id, region, type_of_action (deleted or whitelisted) and timestamp, that would be great for governance and reporting.

**Describe alternatives you've considered**
At the minimum level if the relevant logs can be redirected and saved in a specified S3 bucket as file, that would be a great start.

**Additional context**
I hope this FR makes sense. My apologies if the request has been implemented already or it has been discussed before and was decided not to move forward. Please advise. Thank you.

**Comment by mlevit** [comment]
@tmx-dxiao I think that's a good idea. I think the best way to make that data queriable would be to export it to a CSV file and have it sit in an S3 bucket. That way you can use Athena to query the data. DynamoDB is great and all, but it's not very useful for data interrogation.
