### ISSUE TITLE
EC2 instances are not being detected as part of the cleanup.

### ISSUE THREAD

**Issue by mcueva10** [servian/aws-auto-cleanup#81]
I am focusing on cleaning up EC2 resources including elastic IPs, images, instances, security groups, snapshots, and volumes. When I run the cleanup, all of the resources for EC2 appear in the execution log except EC2 instances. I verified that the AWS account has EC2 instances older than the TTL setting that I set, the role running the app lambda has the EC2 access needed and no errors show up in the lambda logs. Any ideas on what may be causing this?

**Comment by mlevit** [comment]
@mcueva10 can you please deploy the "app" from branch https://github.com/servian/aws-auto-cleanup/tree/ec2-fix and see if that fix has worked for you?

**Comment by mcueva10** [comment]
This worked, thanks! So the issues were the filter that was being applied and the "is_cleaning_enabled" value right?

**Comment by mlevit** [comment]
The filter was actually on the AWS API side. I was filtering on EC2 instances in a state of `running` or `stopped` but when I looked back at that filter, it was comparing the wrong attribute :) Woops
