### ISSUE TITLE
How can the time zone for the execution log dates be changed?

### ISSUE THREAD

**Issue by mcueva10** [servian/aws-auto-cleanup#83]
The date shown for the execution logs is currently in Coordinated Universal Time (UTC). I would like to change the time zone to Eastern Standard Time (EST).

**Comment by mlevit** [comment]
@mcueva10 which one specifically? Screenshot would help :)

**Comment by mcueva10** [comment]
The execution log CSV file date. Attached screenshot, thanks![](url)
![exec-log-date](https://user-images.githubusercontent.com/68252360/131949510-2b62c48f-348e-4720-a0f9-b6fef23d719a.png)

**Comment by mlevit** [comment]
Oh yeah, actually something I've tried before but couldn't get working. I was trying to get the browser's timezone and convert the date. Let me try something again and see if I can get it working.

**Comment by mcueva10** [comment]
Ok thanks, I will also look into it

**Comment by mlevit** [comment]
@mcueva10 test https://github.com/servian/aws-auto-cleanup/tree/execution-date-local-time for me

**Comment by mcueva10** [comment]
This is working, appreciate the help!
