### ISSUE TITLE
Modify the account number header in the top-right corner to show the account alias as well

### ISSUE THREAD

**Issue by mcueva10** [servian/aws-auto-cleanup#84]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like for the header in the top right that shows the account number to show the account alias as well.

**Describe alternatives you've considered**
An output for the account alias could be added and then be referred to in the index.js file. 

**Additional context**
Attached screenshot of header location.
![account-number-header](https://user-images.githubusercontent.com/68252360/131949883-1aa61681-a2e9-4094-ac79-ca4ea90fca09.png)

**Comment by mlevit** [comment]
No way of achieving this via a CloudFormation output. One way would be via a custom API. Not sure if worth the effort.

**Comment by mcueva10** [comment]
Got it, thanks for the response
