### ISSUE TITLE
Show the resource age in the execution log

### ISSUE THREAD

**Issue by atqhg23** [servian/aws-auto-cleanup#86]
**Is your feature request related to a problem? Please describe.**

Yes, the execution log shows the "SKIP - TTL"  action for resources that are under the TTL setting, but it would be useful to know the exact resource age to see how long it will be until a resource is destroyed. This can also be useful in determining what the TTL setting should be set to. I think it would help to include the resource age in the whitelist (both temporary and permanent) as well.

**Describe the solution you'd like**

Add a column in the execution log titled "Age" that shows the age in days of each resource scanned. 

**Describe alternatives you've considered**

Not really sure of an alternative for this.

**Additional context**
Example screenshot below
![resource-age-in-exec-log](https://user-images.githubusercontent.com/68252360/132552015-6fde0ab6-a132-47c1-8d52-d3638a3cfc4a.png)

**Comment by mcueva10** [comment]
Kept thinking about this and I think adding these 3 columns to the execution log may be a good idea:

- **Age**: Resource age in days
- **Destroy In**: The number of days until the resource is destroyed based on the time to live setting. 
- **Signal**: This would be either Green (below 50% of the TTL), Yellow (above 50% of the TTL), or Red (past the TTL). 

Below is a screenshot of what this may end up looking like.
![age-destroyIn-signal-in-exec-log](https://user-images.githubusercontent.com/68252360/132567639-ec9def4d-24a4-48da-aca1-d7fe30e153c2.png)


What are your thoughts on this?

**Comment by bENLiang** [comment]
Love your idea, have you implemented this? 

> Kept thinking about this and I think adding these 3 columns to the execution log may be a good idea:
> 
> * **Age**: Resource age in days
> * **Destroy In**: The number of days until the resource is destroyed based on the time to live setting.
> * **Signal**: Three possible options - This could be **Green** (below 50% of the TTL), **Yellow** (above 50% of the TTL), or **Red** (at or past the TTL).
> 
> Below is a screenshot of what this may end up looking like. ![age-destroyIn-signal-in-exec-log](https://user-images.githubusercontent.com/68252360/132567639-ec9def4d-24a4-48da-aca1-d7fe30e153c2.png)
> 
> What are your thoughts on this?

Love your idea, have you implemented this?
