### ISSUE TITLE
Security groups added to the whitelist showing blank action in execution log when it should say "SKIP - WHITELIST"

### ISSUE THREAD

**Issue by atqhg23** [servian/aws-auto-cleanup#91]
**Describe the bug**
When a security group is added to the whitelist, the action in the execution log is blank.

**To Reproduce**

1. Add a security group to the whitelist
2. Run the cleanup with dry-run on/off
3. Check the execution log action for the security group added to the whitelist
4. The action appear blank

**Expected behavior**
The execution log action should say "SKIP - WHITELIST"

**AWS (please complete the following information):**

- Region: us-east-1

**Comment by mlevit** [comment]
Can you please test https://github.com/servian/aws-auto-cleanup/tree/security-group-fix

**Comment by atqhg23** [comment]
For sure, thanks, I will test this in the morning (EST where I'm at) and will send an update.

**Comment by atqhg23** [comment]
When there are no security groups in the whitelist, the cleanup runs successfully, but this error comes up when there is a security group in the whitelist:
 
```
[ERROR] TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/var/task/src/main.py", line 608, in lambda_handler
    cleanup.run_cleanup()
  File "/opt/python/func_timeout/dafunc.py", line 185, in <lambda>
    return wraps(func)(lambda *args, **kwargs : func_timeout(defaultTimeout, func, args=args, kwargs=kwargs))
  File "/opt/python/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/opt/python/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/var/task/src/main.py", line 316, in run_cleanup
    ec2_class.run()
  File "/var/task/src/ec2_cleanup.py", line 47, in run
    self.security_groups()
  File "/var/task/src/ec2_cleanup.py", line 377, in security_groups
    if resource not in resource_whitelist:
```

**Comment by mlevit** [comment]
Issue fixed. Was comparing the wrong variable against the whitelist :)

**Comment by atqhg23** [comment]
Ah I missed that, will test to confirm

**Comment by atqhg23** [comment]
Apologies for the late response. I just tested this and everything works
