### ISSUE TITLE
Question: Just curious, what was the reason for setting this up with the Serverless Framework? Are you open to allowing others to contribute setting up the infrastructure using terraform as another deployment alternative?

### ISSUE THREAD

**Issue by atqhg23** [servian/aws-auto-cleanup#93]

**Comment by mlevit** [comment]
IMO Serverless is the right framework for deploying application code whereas Terraform/CF are the right frameworks for deploying infrastructure.

Serverless does the hard work of packaging your Lambda functions, creating Lambda Layers, setting up IAM Roles, and creating API Gateways without you needing to explicitly create that infrastructure.

I don't see a need to include Terraform deployment versions as this will just double the maintenance effort.

**Comment by atqhg23** [comment]
I'm not that familiar with the serverless framework, but looking into it a bit, I understand your point of view
