### ISSUE TITLE
Update DynamoDB whitelist Table

### ISSUE THREAD

**Issue by DesAWSume** [servian/aws-auto-cleanup#95]
Whitelist table seem to be adding but not able to remove
For example, Adding new resource to the whitelist works fine, but if we update the resource through json, it did not seem to be updated

**Comment by mlevit** [comment]
Hey @DesAWSume, when you say you update the resource through JSON, what exactly do you mean? Can you please give an example with screenshots to help me understand?

**Comment by DesAWSume** [comment]
Hey @mlevit, thank you for the prompt reply, 

Through the whitelist JSON file, we can define what resource we skip. As the time changed, we might have different requirement where we need to update those,

For example:
We can add a iam role 
iam:role:xxxxxx

and we push the update to AWS, this will add a item in DynamoDB

But if we remove a whitelist resource from whitelist, we comment out the block and then pushed the update
DynamoDB whitelist table still keep the old resource.

I am thinking maybe we need to add a logic to also update the dynamoDB whitelist table like the settings as well

what is your thought on this?

**Comment by mlevit** [comment]
Ah right. The `auto-cleanup-whitelist.json` file that you're modifying is a one time use for the setup of the whitelist table. It should not be used to then add resources to the whitelist.

Instead, you need to install the API and WEB components of AWS Auto Cleanup. This will enable you to add, update, and delete all whitelist operations through an easy to use web interface.
