### ISSUE TITLE
Dry Run disable in app

### ISSUE THREAD

**Issue by luoyimu1** [servian/aws-auto-cleanup#96]
Dear Team,

I'd like to disable dry_run and delete the resources.

What I can see from the code is that I need to change both `version` and `dry_run` in the data file to fulfil the requirement. Is it correct?

Thanks in advance.

**Comment by mlevit** [comment]
Hey @luoyimu1. The files are only there for the initial deployment. Once the app is deployed and run for the first time, you can change all the settings through the DynamoDB table `auto-cleanup-app-prod-settings`.

View the items in the table and modify the `general` key setting the `dry_run` flag to `false`.

**Comment by luoyimu1** [comment]
Hey @mlevit , thanks a lot for the info.
We're actually trying to manage the changes in the source code (make changes in the code-> "npm run deploy") so that eventually we'll be able to put it in the pipeline and leave the website as the only source of management GUI.
I may test it out on my side and let you know if the way I described in the question works or not.
Cheers,

**Comment by mlevit** [comment]
I get what you mean. Updating the version and re-running the deployment will work, but it's not the intended use for that.

Whenever I release new versions of Auto Cleanup and need to push new settings to you, I increase the `version` which will force the update on your side.
