### ISSUE TITLE
Deploying of api throws an error Rest API id could not be resolved.

### ISSUE THREAD

**Issue by membra** [servian/aws-auto-cleanup#99]
Hello, 

While trying to set up a pipeline to deploy and run aws-auto-cleanup noticed that when deploying api component

 npm run deploy -- --region ap-southeast-2

the stack looks to be deployed fine, all resources inside it as well

But in the very end npm throws this error:
Rest API id could not be resolved.

and exits with status 1 (error)

Attaching full log:
[apideploylogs.txt](https://github.com/servian/aws-auto-cleanup/files/7805138/apideploylogs.txt)

When I was deploying initially from local machine it didn't matter much as I checked that it deployed fine and was working after that,
But now it is failing pipeline because of that.

What exactly is it trying to resolve and why?
Thanks!

**Comment by membra** [comment]
The error seems to have disappeared when I removed following from serverless.yml

  tracing:
    apiGateway: true
    lambda: true

Any requirements from the aws-auto-cleanup to have it?

**Comment by mlevit** [comment]
Hey @membra thanks for raising this, I'm currently taking a little break and will be back in a week or so to look into this.

**Comment by mlevit** [comment]
@membra is this still an issue for you? I've upgraded to Serverless V3, not sure if that changes anything or not.
